Refactor
Star-Academy/Winter99Co-Op-Amirhossein-Arabzadeh pull request #2
Opened 2021-02-09 09:12 UTC by amirarab888

2021-02-11 06:54 UTC, amkamir82 requested changes

2021-02-11 06:54 UTC, amkamir82 commented on Phase1/src/main/java/HashedInvertedIndex.java
> +
change parameter type to HashedInvertedIndex for more generality.

2021-02-11 06:54 UTC, amkamir82 commented on Phase1/src/main/java/HashedInvertedIndex.java
> +
remove your code that have been comment

2021-02-11 06:54 UTC, amkamir82 commented on Phase1/src/main/java/HashedInvertedIndex.java
> +
long method

2021-02-14 16:19 UTC, mostmand requested changes

2021-02-14 16:19 UTC, mostmand commented on Phase1/.idea/aws.xml
> +<?xml version="1.0" encoding="UTF-8"?>
فایل‌های پوشه‌ی
.idea
نباید در گیت باشند از فایل
gitignore
مناسب استفاده کن برای این کار می‌تونی از این سایت کمک بگیری
gitignore.io

2021-02-14 16:19 UTC, mostmand commented on Phase1/output.txt
>  Contents of file 58155
این فایل می‌تواند در گیت ایگنور قرار بگیرد

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/ArrayListOperator.java
> +        return tempResult;
چرا
tempResult
در خروجی تابع بازگردانده می‌شود؟

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/ArrayListOperator.java
> +        return listCalculator.andResultSet(docsWitchHasPlusWords, result);
which not witch!😅

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/ArrayListOperator.java
> +        return listCalculator.andResultSet(docsWitchHasPlusWords, result);
البته شاید اسمی مثل
docsContainingPlusWords
قشنگتر باشه

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/ArrayListOperator.java
> +        //clean the result of docs which have not at least one of the plus sugned words
بهتر است این کامنت حذف شود و از اسم مناسب‌تر برای تابع استفاده شود مثلاً اسم این تابع به جای
andResultWithSetOfDocsContainingPlusSignedWords
می‌تواند
removeDocsWithoutPlusWords
باشد

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/Controller.java
> +    List<String> getResult(List<String> plusSignedInputWords, List<String> minusSignedInputWords, List<String> unSignedInputWords);
برای این تابع اسم مناسبی متناسب با کاری که باید انجام دهد انتخاب شود
getResult
خیلی کلیه

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/Controller.java
> +    //HashMap<String, List<String>> getInvertedIndexTable();
کد کامنت شده پاک شود

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/Controller.java
> +public interface Controller {
اسم اینترفیس خیلی کلیه
مثلا
IndexController
یا
SearchController
بهتره یا حتی چیزی مثل
searchService

اما در کل به نظرم این دو تا تابع اومدن توی یه اینترفیس مناسب نیست چون یکیشون ایندکس می‌سازه اون یکی کارش سرچه و خیلی ربطی به هم ندارن می‌تونه دو تا کنترلر جداگانه باشه

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/InvertedIndex.java
> +    //produces the result ArrayList for the search action
از
javadoc
به جای کامنت بهره گرفته شود

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/InvertedIndex.java
> +    List<String> prepareResultSet();
این طراحی جالبی واسه اینترفیس نیست که عبارت مورد جستجو اینجا توی ورودی تابع گرفته نمیشه و به جاش توی پیاده سازی رفتی توی کانستراکتور گرفتی

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/HashInvertedIndex.java
> +        table = InvertedIndexController.getInvertedIndexTable();
این که اینجا از
InvertedIndexController
به صورت استاتیک استفاده شده خیلی بده
به نظرم
InvertedIndexController
باید از حالت استاتیک در بیاد و این جا هم به حای این که
table
ازش گرفته بشه و به تابع‌های 
ListOperator
پاس داده بشه توی خود
ListOperator
از
InvertedIndexController
استفاده بشه هم چنین نباید
InvertedIndexController
جدولش رو در اختیار بقیه بذاره و به جاش باید بهشون یه سری تابع ارائه بده مثلا تابعی که داکیومنت‌هایی که یک عبارت درشون هست رو برگردونه

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/HashInvertedIndex.java
> +        table = InvertedIndexController.getInvertedIndexTable();
اما در کل من متوجه نشدم چرا یه کلاس داری
InvertedIndexController
و یه اینترفیس داری
InvertedIndex
این دو تا نباید یکی باشن؟

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/InvertedIndexController.java
> +    public List<String> getResult(List<String> plusSignedInputWords, List<String> minusSignedInputWords, List<String> unSignedInputWords) {
به نظرم کار این کنترلر باید این باشه که یه آبجکت از جنس
InvertedIndex
بسازه و برگردونه بعد یه
searchController
داشته باشی که توی کانستراکتور یه
InvertedIndex
بگیره و با استفاده از اون سرچ ارائه بده

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/IteratingListCalculator.java
> +        Set<String> docsWitchHasMinusWords = new HashSet<>();
which!

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/LineByLineTokenizer.java
> +        File file = new File(dir, fileName);
چند خط ساختن اسکنر می‌تونه یه تابع بشه

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/LineByLineTokenizer.java
> +        Scanner scanner = null;
اسکنر کی
close
میشه؟

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/LineByLineTokenizer.java
> +    private List<MyToken> tokens = new ArrayList<>();
چرا
tokens
توی اسکوپ کلاس تعریف شده و به صورت محلی تعریف نشده؟

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/MyToken.java
> +    public void setDoc(String doc) {
وجود تابع ست برای داکیومنت چه استفاده‌ای داره؟ مگه تو کانستراکتور ست نمیشه؟ و این که مگه ممکنه داکیومنت یه توکن عوض بشه؟

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/MyToken.java
> +        if (this.getTerm().compareTo(((MyToken) o).getTerm()) == 0) {
باید چک بشه که آبجکت
o
از جنس
MyToken
باشه اگه نباشه کستی که انجام شده اکسپشن می‌خوره

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/MyFileReader.java
> +    //takes hashedInvertedIndex to have a HashedInvertedIndex to operate on the tokens
نوشتن
javadoc
به جای کامنت توصیه میشه

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/MyFileReader.java
> +public interface MyFileReader {
نام مناسب‌تری برای اینترفیس انتخاب کن کلمه‌ی
My
خیلی مناسب نیست

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/MyToken.java
> +public class MyToken implements Comparable {
کلمه‌ی
My
چندان مناسب نیست خود
Token
چه مشکلی داره؟

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/MyToken.java
> +public class MyToken implements Comparable {
البته این شاید توکن نباشه چون وجود یه توکن تو یه داکیومنت رو نشون میده میشه اسمش رو گذاشت مثلاً
WordOccurrence

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/MyView.java
> +    private static void partitionInputs(String searchingTerm) {
این تابع بهتره به جای این که بره 
plusSignedInputWords و minusSignedInputWords  و unSignedInputWords 
رو توی کلاس ست کنه یه کلاسی برگردونه که شامل این سه تا باشه این طوری خیلی راحت‌تر میشه براش تست نوشت هم چنین دیگه
side effect
نداره و چند ترد به طور هم‌زمان می‌تونن از این تابع استفاده کنن

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/TokensTableMerger.java
> +            table.put(tokens.get(i).getTerm(), new ArrayList<>(docs));
این باگ داره چرا که فرض کن توکن شماره 0 کلمه‌ی «علی» باشه بعد توکن شماره‌ی 1 یه کلمه‌ی دیگه باشه بعد دوباره توکن شماره 2 کلمه‌ی «علی» باشه در این صورت نتیجه فقط داکیومنت توکن شماره 2 رو برای کلمه‌ی «علی» نگه میداره یعنی منظورم اینه که اگه یه کلمه‌ای رو قبلا دیده باشیم لیست داک‌هاش با یه
ArrayList
جدید جایگزین میشه

2021-02-14 16:19 UTC, mostmand commented on Phase1/src/main/java/TokensTableMerger.java
> +    public HashMap<String, List<String>> createHashTableOfWords(List<MyToken> tokens) {
به غیری از باگی که در کامنت بعدی توضیح داده شده کلا میشه این کد رو خیلی ساده تر زد مثلا این طوری
```java
for (MyToken token: tokens){
    if (!table.contains(token.getTerm()){
        table.put(new ArrayList<String>());
    }
    table.get(token.getTerm()).add(token.getDoc());
}
```

2021-02-14 18:10 UTC, mostmand commented
طراحی امیرمهدی رو یه بررسی بکن

2021-02-15 05:27 UTC, amirarab888 commented on Phase1/src/main/java/ArrayListOperator.java
> +        return tempResult;
به جهت این که ریزالت را برابر این قرار میدهیم و در خود تابع ریزالت را تغییر نمی دهیم و این که تابع قابل تست کردن میشود.

2021-02-15 05:33 UTC, amirarab888 commented on Phase1/src/main/java/Controller.java
> +    List<String> getResult(List<String> plusSignedInputWords, List<String> minusSignedInputWords, List<String> unSignedInputWords);
getSetOfDocsForUser
مناسب است؟

2021-02-15 06:54 UTC, amirarab888 commented on Phase1/src/main/java/HashInvertedIndex.java
> +        table = InvertedIndexController.getInvertedIndexTable();
بحث استاتیک بودن رو درست کردم
ولی
لیست اپراتور صرفا داره یه سری عملیات انجام میده روی لیست هایی که بهش داده میشه, و مسیولیتی در قبال چیز دیگری نداره از طرفی در واقع اون تابع هایی که شما عرض میکنید رو من جدا کردم تو یه اسنترفیس که کد تمیز تر باشه

2021-02-15 06:55 UTC, amirarab888 commented on Phase1/src/main/java/HashInvertedIndex.java
> +        table = InvertedIndexController.getInvertedIndexTable();
در مورد این که چرا دو تا کلاس هست هم, اینه که کنترولر رو خواستم جدا کنم

2021-02-15 06:58 UTC, amirarab888 commented on Phase1/src/main/java/InvertedIndexController.java
> +    public List<String> getResult(List<String> plusSignedInputWords, List<String> minusSignedInputWords, List<String> unSignedInputWords) {
آبجکت از جنس 
InvertedIndex 
رو در خود 
MySearchController 
ساختم
مشکلی داره؟

2021-02-15 07:08 UTC, amirarab888 commented on Phase1/src/main/java/LineByLineTokenizer.java
> +        Scanner scanner = null;
در آخر تابع
tokenizOneDoc
گذاشتم, خوبه؟

2021-02-15 07:09 UTC, amirarab888 commented on Phase1/src/main/java/LineByLineTokenizer.java
> +    private List<MyToken> tokens = new ArrayList<>();
چون در تابع
addNewToken
به 
tokens
آیتم اضافه میشه
دلیل خوبی نیست؟

2021-02-15 07:14 UTC, amirarab888 commented on Phase1/src/main/java/MyToken.java
> +        if (this.getTerm().compareTo(((MyToken) o).getTerm()) == 0) {
اگه از این جنس نبود چه چیزی
return
بشه؟

2021-02-15 07:25 UTC, amirarab888 commented on Phase1/src/main/java/MyView.java
> +    private static void partitionInputs(String searchingTerm) {
یک کلاس جدا برای 
partitionInputs
تعریف شد
مناسب است؟

2021-02-15 07:26 UTC, amirarab888 commented on Phase1/src/main/java/TokensTableMerger.java
> +            table.put(tokens.get(i).getTerm(), new ArrayList<>(docs));
امکان نداره جون لیستی که بهش میدیم سورت شده است.

2021-02-16 07:26 UTC, merged