Phase04
Star-Academy/Winter99Co-Op-Amirhossein-Arabzadeh pull request #4
Opened 2021-02-18 16:38 UTC by amirarab888

2021-02-26 21:45 UTC, saj76 commented on Phase04/Phase04/IDeserialize.cs
> +        abstract IFileReader FileReader { get; set;}
چرا این ها 
abstract
تعریف شدند داخل یک 
interface
اگر 
abstract 
رو نذاری هم مشکلی پیش نمیاد

2021-02-26 21:48 UTC, saj76 commented on Phase04/Phase04/OrderedEnumerableResultPrinter.cs
> +                return;
میتونی خطا هم بدی که کاربر بدونه چیز اشتباهی پاس داده

2021-02-26 21:51 UTC, saj76 commented on Phase04/Phase04/Program.cs
> +        private static IEnumerable<StudentInfo> JoinScoresWithStudents(List<Student> students, List<Course> scores)
شاید یه اسم بهتر متناسب با خروجی متد میذاشتی بهتر بود که کارایی متد بیشتر از اسمش مشخص باشه

2021-02-26 21:53 UTC, saj76 commented on Phase04/Phase04/Student.cs
> +        public override bool Equals(object obj)
منطقش ایراد نداره؟ نام و نام خانوادگی اگه متفاوت باشه چی؟

2021-02-26 21:57 UTC, saj76 commented on Phase04/Phase04/ICourse.cs
> +    public interface ICourse
وجود این 
interface
ضروری نیست. داری خیلی آینده نگری میکنی به نظر
:)

2021-02-26 21:58 UTC, saj76 commented on Phase04/Phase04/IStudent.cs
> +    public interface IStudent
وجود این یکی 
interface
هم ضروری نیست به نظرم

2021-02-26 21:59 UTC, saj76 requested changes
لطفا این مواردی که نوشتم رو یه بررسی مجدد بکن

2021-02-27 03:44 UTC, amirarab888 commented on Phase04/Phase04/Student.cs
> +        public override bool Equals(object obj)
student number 
یکتا در نظر گرفتم

2021-02-28 08:21 UTC, saj76 approved these changes

2021-02-28 10:07 UTC, mostmand requested changes
محاسبه‌ی معدل و سه دانش‌آموز برتر که اصل منطق برنامه بوده است تست نشده است

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/Deserialize.cs
> +    public class Deserialize : IDeserialize
نام کلاس نباید فعل باشد

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/Deserialize.cs
> +        public IFileReader FileReader { get; set; }
چرا
FileReader
به صورت
public
تعریف شده است در حالی که می‌تواند
private readonly
باشد

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/ICourse.cs
> +    public interface ICourse
با سجاد موافقم توی کلاس‌های مدل لازم به تعریف اینترفیس نیست

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/IDeserialize.cs
> +    public interface IDeserialize
نام اینترفیس نباید فعلی باشه مثلاً
IDeserializer
شاید بهتر باشه

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/IDeserialize.cs
> +        IFileReader FileReader { get; set;}
اینجا نباید
IFileReader
باشه

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/IFileReader.cs
> +        abstract string GetTextOfFile(string relatedPath);
کلمه‌ی کلیدی
abstract
توی اینترفیس بی معنیه چرا که همه‌ی تابع ها توی اینترفیس پیاده‌سازی ندارن

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/IOrderedEnumerableResultPrinter.cs
> +        void PrintResult(IOrderedEnumerable<StudentInfo> orderByResult);
چرا
IOrderedEnumerable?
می‌تونست خود
IEnumerable
ورودی گرفته بشه

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/IStudent.cs
> +    public interface IStudent
این اینترفیس لازم نیست

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/OrderedEnumerableResultPrinter.cs
> +                throw new ArgumentException();
اکسپشن
ArgumentNullException
در این مواقع بهتره این طوری مثلاً
```csharp
throw new ArgumentNullException(nameof(orderByResult));
```

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/OrderedEnumerableResultPrinter.cs
> +            for (var i = 0; i < 3; i++)
پیدا کردن دانش‌آموزان برتر نباید بر عهده‌ی این کلاس باشد و این کلاس صرفاً وظیفه‌ی نمایش دارد و ورودی که به این تابع داده می‌شود بهتر است تنها شامل سه دانش‌آموز برتر باشد

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/OrderedEnumerableResultPrinter.cs
> +                Console.WriteLine(student.FirstName + " " + student.LastName + " " + student.AverageScore);
نحوه‌ی ساخت استرینگ برای هر
student
می‌تواند در متد
ToString
کلاس
Student
پیاده سازی شود

2021-02-28 10:07 UTC, mostmand commented on Phase04/Phase04/OrderedEnumerableResultPrinter.cs
> +                Console.WriteLine(student.FirstName + " " + student.LastName + " " + student.AverageScore);
هم‌چنین استفاده از
string interpolation
کد را خواناتر می‌کند
```csharp
$"{student.FirstName} {student.LastName} {student.AverageScore}"
```

2021-02-28 16:44 UTC, amirarab888 commented on Phase04/Phase04/OrderedEnumerableResultPrinter.cs
> +            for (var i = 0; i < 3; i++)
همین طور هست

2021-03-01 06:28 UTC, merged