Phase08
Star-Academy/Winter99Co-Op-Amirhossein-Arabzadeh pull request #6
Opened 2021-03-06 13:48 UTC by amirarab888

2021-03-08 21:22 UTC, mostmand requested changes
احسنت بسیار عالی
یه تعدادی کامنت گذاشتم ببین
راستی چرا درصد پوشش تست‌هات نسبت به قبل کاهش یافته؟

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexLibrary/Doc.cs
> +        public override bool Equals(object obj)
اگه دقت کنی خود گیت‌هاب هم به این ایراد گرفته که تابع
Equals
رو پیاده سازی کردی ولی تابع
GetHashCode
رو پیاده سازی نکردی

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexLibrary/HashTableCreator.cs
>                  if (tableOfWordsAsKeyAndContainingDocsAsValue.ContainsKey(wordOccurrence.Term))
داخل حلقه‌ی
foreach
می‌تونه خودش به عنوان یه تابع استخراج بشه

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexLibrary/InvertedIndexContext.cs
> +            optionsBuilder.UseSqlServer(@"Server=DESKTOP-PT8A28F;Database=InvertedIndexDb;Trusted_Connection=True;");
به جای
DESKTOP-PT8A28F
می‌تونی
.
یا
localhost
بزنی

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexLibrary/ListCalculator.cs
> +            var setOfContainingDocsOfWords = IterateWordsListToTakeContainingDocsFromTable(words);
نام تابع باید گویای این باشه که چه کار انجام میده نه این که کار رو چگونه انجام میده مثلا این‌جا کسی که تابع رو صدا می‌زنه لازم نیست بدونه داری روش
Iterate
می‌کنی صرفا لازمه بدونه که کلمه‌های موجود توی دیتابیس رو بهش میدی

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexLibrary/ListOperator.cs
> +            return (from unSignedWord in unSignedWords
شور
Linq
رو در آوردن! 😂
یه جوری بنویس کسی که کد رو می‌خونه راحت بفهمه داره چه اتفاقی میفته

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexLibrary/SearchItem.cs
> +        public override bool Equals(object obj)
این‌جا هم باز
Equals
رو
ovverride
کردی ولی 
GetHashCode()
رو نه

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexLibrary/Tokenizer.cs
> +            foreach (var term in terms)
به نظر چاقوی جراحی رو تو دل بیمار جا گذاشتی!

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexTest/HashTableCreatorTest.cs
> +            //Assert.Equal(expectedTable, actualTable);
چرا
assertion
کامنت شده؟

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexTest/ListCalculatorTest.cs
> +            var sampleInputList = (from number in  Enumerable.Range(1, 60)
استفاده از سینتکس
lamda
به نظرم خواناتر از سینتکس کوئریه یعنی این جوری:
```csharp
var sampleInputList = Enumerable.Range(1, 60)
    .Select(number => number.ToString())
    .ToList();
```

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexTest/ListCalculatorTest.cs
> +            var sampleInputList = (from number in  Enumerable.Range(1, 60)
جاهای دیگه هم دیدم از سینتکس کوئری استفاده کردی اونا هم به نظرم با سینتکس
lambda
خواناتره

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexTest/TableProvider.cs
> +    public class TableProvider
این کلاس خالی چیه؟

2021-03-08 21:22 UTC, mostmand commented on Phase05/InvertedIndexTest/TestDbContextFactory.cs
> +                .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString()).Options;
در چنین شرایطی استفاده از
named argument
رو توصیه نمی‌کنم چرا که شما داری خودت رو به نام ورودی تابع وابسته می‌کنی و اگه پس فردا اون لایبرری تو ورژن جدیدش اسم متغیر ورودی رو عوض کرد کامپایل ارور می‌خوری
بعضی موارد یه تابع یه عالمه ورودی آپشنال می‌گیره که شما می‌خوای یکیش رو مقدار دهی کنی اون‌جا
named argument
کار رو راحت می‌کنه

2021-03-31 06:15 UTC, mostmand approved these changes

2021-03-31 06:15 UTC, mostmand commented on Phase05/InvertedIndexLibrary/Tokenizer.cs
> +        private int i = 0;
متغیر استفاده نشده حذف شود

2021-03-31 06:15 UTC, mostmand commented on Phase10/Phase10/ImportRun/ImportRun.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
این پول ریکوئست مگه برای فاز 8 نیست؟ پس چرا فایلای فاز 10 توش هست؟

2021-03-31 06:29 UTC, amirarab888 commented on Phase10/Phase10/ImportRun/ImportRun.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
برای اینکه برنج فاز ده رو از رو این برنچ زده بودم

2021-03-31 06:30 UTC, merged