Phase10
Star-Academy/Winter99Co-Op-Amirhossein-Arabzadeh pull request #7
Opened 2021-03-18 07:54 UTC by amirarab888

2021-03-19 14:57 UTC, mahdimalverdi requested changes

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/Addresses.cs
> +        public const string FolderRelativePath = "../../../../Resources/BigEnglishData";
در مورد AppSetting.json  مطالعه کن و از اون به جای این فایل استفاده کن

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/ElasticResponseValidator.cs
> +            switch (exception.FailureReason)
یه دیکشنری درست کن تمام مقادیر رو بر اساس هر حالت داخل اون بریز بعد از اون دیکشنری بخون و چاپ بکن
الان داری یه کار تکراری رو چند بار می نویسی

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/FileReader.cs
> +                throw new FileNotFoundException(fileNotFoundException.Message);
نیازی به این کار نیس
تنها نیازه کد زیر رو نویس

```CSharp
throw;
```

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/IndexDefiner.cs
> +                .Setting(KeyWords.MaxNgramDiff, 7)
7 رو توی مقدار کانست بریز

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/IndexDefiner.cs
> +                    .MinGram(3)
این مقدار ها رو توی کانست بریز

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/InputGetter.cs
> +            var input = Console.ReadLine()?.ToLower();
نیاز نیس متغییر بگیری مستقیم ریترن کن

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/Phase10Library.csproj
> +      <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
از System.Test.Json استفاده کن سریع تره

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/QueryCreator.cs
> +        public QueryContainer GetQueryContainer(StringBuilder unsignedWordString, StringBuilder plusSignedWordString,
حس می کنم این مقادیر رو باید از کانستراکتور بگیری
و بعد تابع زیر رو به تابع های کوچیک بشکون

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/SearchController.cs
> +        private IEnumerable<string> GetResultSetOfSearch(IEnumerable<string> unsignedWords,
فاصله بیان تابع هات رو رعایت کن
فاصله نداشتن زشت میکنه کد رو

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/SearchController.cs
> +            CreateWordStrings(unsignedWords, plusSignedWords, minusSignedWords, out var plusSignedWordString,
استفاده از out مکروهه یه فکر دیگه بکن براش

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/SearchController.cs
> +            var unsignedWordString = new StringBuilder();
از String.Join استفاده کن کل این تابع نیاز نیست

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10LibraryTest/DocTest.cs
> +            new object[] {"ProperName","    "},
مقادیر رشته ای رو به کانست تبدیل کن

2021-03-19 14:57 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10LibraryTest/FileNamesExtractorTest.cs
> +        [Theory]
فاصله ...

2021-03-28 14:30 UTC, mahdimalverdi requested changes

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/SearchController.cs
> +            foreach (var unsignedWord in unsignedWords)
از string.join استفاده کن برای این تابع و تابع های مشابه

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/Settings.cs
> +    public class Indexes
هر کلاس یک فایل

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/QueryCreator.cs
> +            return new MatchQuery
حس نمی کنی این تابع و دوتا تابع پایینش خیلی شبیه هستن؟

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/Doc.cs
> +        public string Name { get;}
ترتیب اجزای کلاست به این ترتیب باشه
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/Doc.cs
> +                Console.WriteLine(exception.Message);
در مورد Logger بخون و ازش استفاده کن این جور موارد

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/ElasticResponseValidator.cs
> +
فاصله هات تمیز نیز تو کدت

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/FileReader.cs
> +                var content = File.ReadAllText(filePath);
مستقیم ریترن کن نریز تو متغییر

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/SearchController.cs
> +                "Content");
استرینگ هیج نداشته باش تو کدت همه رو بریز تو یه مقدار کانست

2021-03-28 14:30 UTC, mahdimalverdi commented on Phase10/Phase10/Phase10Library/SearchController.cs
> +                .Size(1000)
عدد هم نداشته باش من الان نمی فهمم این 1000 چیه و از کجا امده

2021-03-28 15:26 UTC, mostmand requested changes

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/ImportRun/appsettings.json
> +    "FolderRelativePath": "../../../../Resources/BigEnglishData",
استفاده از کانفیگ خیلی خوبه ولی به نظرم صرفا آدرس فایل‌ها و آدرس الستیک و نام ایندکس باید کانفیگی باشن بقیه به نظرم نباید کاربر بتونه عوضشون کنه

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/ImportRun/appsettings.json
> +    "HttpLocalhost": "http://localhost:9200"
بخش‌های کانفیگ رو مرتب تر کن مثلا یه بخش داشته باش
Elasticsearch
که توش یه 
Uri
داشته باشه و یه
IndexName
از اون طرف هم آدرس فایل‌ها یه آبجکت جیسون دیگه باشه

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/Doc.cs
> +                Console.WriteLine(exception.Message);
مهدی درست میگه این وابستگی به کنسول باعث میشه
Dependency Inversion Principle
نقض بشه و قابلیت تست از بین بره

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/Doc.cs
> +        private void TryValidateContent(string content)
تابع‌هایی که با اسم
Try
شروع میشن توی سی‌شارپ معمولا اکسپشن نمیدن مثل
TryGetValue
توی کلاس دیکشنری به نظرم
ValidateContent
نام مناسب‌تریه

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/ElasticClientFactory.cs
> +            connectionSettings.EnableDebugMode();
استفاده از دیباگ مود در
production
خوب نیست چون باعث افت پرفورمنس میشه می‌تونی این کارو بکنی
```csharp
#if DEBUG
    connectionSettings.EnableDebugMode();
#endif

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/ElasticClientFactory.cs
> +            connectionSettings.EnableDebugMode();
این جوری فقط توی بیلد دیباگ این خط کامپایل میشه و توی بیلد ریلیز این اتفاق نمی‌افته

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/ElasticResponseValidator.cs
> +        {
احسنت این کار بهتر از سوییچ کیس نوشتنه ولی باز هم یه ایراد داره اگه گفتی ایرادش چیه؟ هم‌چنین چه جوری میشه این ایرادو برطرف کرد؟

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/ElasticResponseValidator.cs
> +            Console.WriteLine(_failureReasonsAndMessages[exception.FailureReason]);
این‌جا هم استفاده از
ILogger
توصیه میشه به جای استفاده از
Console.WriteLine()

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/FileNamesExtractor.cs
> +        private string[] TryToGetFilesRelatedPath(string folderRelativePath)
متد‌هایی که نامشون با
Try
شروع میشه معمولا اکسپشن نمیدن

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/FileReader.cs
> +        private string[] GetFilePathsArray(IEnumerable<string> filePaths)
علت این کار چیه؟ چه اصراریه حتما آرایه باشه؟ خود
IEnumerable<string>
مگه چه مشکلی داره؟

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/FileReader.cs
> +                var content = File.ReadAllText(filePath);
مهدی به نظرم خیلی فرقی نمی‌کنه حتی دیباگینگ رو ساده‌تر می‌کنه این که بریزتش توی متغیر

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/FileReader.cs
> +                Console.WriteLine(fileNotFoundException);
این‌جا هم استفاده از
Console.WriteLine()
اصل
Dependency Inversion
رو نقض کرده و بهتره از
ILogger
استفاده بشه

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/IndexDefiner.cs
> +            Console.WriteLine(response.ServerError);
این‌جا هم باز
Console.WriteLine
بده

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/IndexDefiner.cs
> +                    .Filters(_settings.TokenFilters.LowerCase, _settings.TokenFilters.WordDelimiter,
خوبه هر فیلتری رو توی یه خط بنویسی

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/QueryCreator.cs
> +            return new MatchQuery
مهدی حرفت درسته که این سه تا کوئری قسمت تکراری دارن ولی به نظرم خوب نیست که یه تابع بشن و این طوری خواناتره و منطق رو بهتر می‌رسونه هم چنین لازم به ذکره که این که اینا یکسان شدن به نظرم شانسیه و به خاطر منطق قضیه نیست

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/SearchController.cs
> +                minusSignedWordString.Concat(" " + minusSignedWord);
وقتی داری
for
می‌زنی و به یه استرینگ مقادیری رو اضافه می‌کنی معمولاً استفاده از
StringBuilder
یا
string.Join
توصیه میشه چون از لحاظ پرفورمنسی بهتره علتش هم اینه که
stringها
immutable
هستن

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/SearchController.cs
> +            foreach (var unsignedWord in unsignedWords)
عه تو هم به این موضوع اشاره کردی!

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/Settings.cs
> +        public override string ToString()
این متد کجا استفاده میشه که پیاده‌سازی شده؟

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/View.cs
> +            Console.WriteLine(docsSearchingResultSet.Count());
این
Console.WriteLine
بهتره بره داخل یه کلاسی که نمایش رو به عهده داره و از اینترفیسش اینجا استفاده بشه چون فرض کن یه موقع دیگه بخوایم یه جور دیگه نتایج رو نمایش بدیم

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10Library/View.cs
> +            Console.WriteLine(docsSearchingResultSet.Count());
هم چنین خطوط بعدش که خود نتایج رو داره چاپ می‌کنه

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10LibraryTest/ElasticClientFactoryTest.cs
> +            var configuration = new ConfigurationBuilder()
توی تست لازم نیست کانفیگت واقعی باشه

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10LibraryTest/FileNamesExtractorTest.cs
> +
این خطوط خالی وسط کد قشنگ نیست پاکشون کن

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10LibraryTest/ImporterTest.cs
> +            var configuration = new ConfigurationBuilder()
این تستت یونیت تست نیست چون از کلاینت واقعی استفاده کردی بیش‌تر
Integration Test عه
می‌تونی
IElasticClient
رو ماک کنی

2021-03-28 15:26 UTC, mostmand commented on Phase10/Phase10/Phase10LibraryTest/IndexDefinerTest.cs
> +            var configuration = new ConfigurationBuilder()
این تست هم باز یونیت تست نیست و خوبه که
IElasticClient
ماک بشه و صرفا کال شدن تابع مورد نظر توی
IElasticClient
با آرگومان مناسب بررسی بشه

2021-03-30 04:56 UTC, amirarab888 commented on Phase10/Phase10/Phase10LibraryTest/ElasticClientFactoryTest.cs
> +            var configuration = new ConfigurationBuilder()
خب این جوری اگه کانفیگ اشتباه باشه تست ها هم فیل میشه, بهتر نیست؟

2021-03-30 04:56 UTC, amirarab888 commented on Phase10/Phase10/Phase10LibraryTest/ImporterTest.cs
> +            var configuration = new ConfigurationBuilder()
آخه هدف من هم 
integration
بود چون یونیت تستش به نظرم جالب نیست

2021-03-30 09:25 UTC, mostmand approved these changes

2021-03-30 09:25 UTC, mostmand commented on Phase10/Phase10/Phase10Library/Addresses.cs
> +        public string host { get; set; }
*Host

2021-03-30 09:25 UTC, mostmand commented on Phase10/Phase10/Phase10Library/ElasticResponseValidator.cs
> +                .Where(type => !type.IsPublic)
چرا اونایی که پابلیک نیستن؟

2021-03-30 09:25 UTC, mostmand commented on Phase10/Phase10/Phase10LibraryTest/FileNamesExtractorTest.cs
> +            const int StartIndexOfFileName = 39;
به جای عدد 39 بهتره بنویسی:
```csharp
int startIndexOfFileName = relativeDirectoryPath.Length + 1;
```

2021-03-31 05:43 UTC, merged